# Setup
title:        WorkFor.LA
tagline:      It takes a year, but it’s worth a lifetime!
baseurl:      "http://www.workfor.la"
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
